#ifndef NEWTUA_H
#define NEWTUA_H

#pragma once

/* Generated by cbindgen from newtua-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Status codes returned across the boundary. Values are stable ABI.
 */
typedef enum {
  NtuaStatus_Ok = 0,
  NtuaStatus_Io = 1,
  NtuaStatus_UnknownFormat = 2,
  NtuaStatus_Unsupported = 3,
  NtuaStatus_Encrypted = 4,
  NtuaStatus_WrongPassword = 5,
  NtuaStatus_Corrupt = 6,
  NtuaStatus_PathTraversal = 7,
  NtuaStatus_MissingVolume = 8,
  NtuaStatus_InvalidIndex = 9,
  /*
   A required pointer argument was null.
   */
  NtuaStatus_NullArg = 100,
  /*
   A C string argument was not valid UTF-8.
   */
  NtuaStatus_Utf8 = 101,
  /*
   A panic was caught at the boundary.
   */
  NtuaStatus_Panic = 102,
} NtuaStatus;

typedef enum {
  NtuaEntryKind_File = 0,
  NtuaEntryKind_Dir = 1,
  NtuaEntryKind_Symlink = 2,
} NtuaEntryKind;

/*
 Opaque archive handle (returned as `NtuaArchive*`).
 */
typedef struct NtuaArchive NtuaArchive;

/*
 Open options. Both fields are nullable UTF-8 C strings.
 */
typedef struct {
  const char *password;
  const char *encoding;
} NtuaOpenOptions;

/*
 A borrowed view of one entry. String/byte pointers belong to the
 `NtuaArchive` and are valid until `ntua_free`. Copy if you need them longer.
 */
typedef struct {
  const char *path;
  uintptr_t path_len;
  const uint8_t *path_raw;
  uintptr_t path_raw_len;
  NtuaEntryKind kind;
  uint64_t size;
  bool has_mode;
  uint32_t mode;
  bool is_encrypted;
  bool has_mtime;
  int64_t mtime_unix;
} NtuaEntry;

/*
 Extraction options. Nullable C strings; `selection`/`selection_len` of
 null/0 means "all entries".
 */
typedef struct {
  const char *dest;
  const char *password;
  const char *encoding;
  bool wrapper;
  bool strict;
  bool preserve;
  const uintptr_t *selection;
  uintptr_t selection_len;
} NtuaExtractOptions;

/*
 Progress notification passed to the callback during extraction.
 */
typedef struct {
  uintptr_t index;
  /*
   Entry path (UTF-8) on `started`; null otherwise.
   */
  const char *path;
  uint64_t bytes_written;
  uint64_t entry_size;
  bool started;
  bool finished;
} NtuaProgress;

/*
 Progress callback: return 0 to continue, nonzero to abort. Nullable — the
 `Option` makes cbindgen emit a plain, null-able C function pointer (and lets
 Swift import it), and callers pass `None` for "no progress".
 */
typedef int (*NtuaProgressFn)(void *ctx, const NtuaProgress *progress);

/*
 Result of an extraction.
 */
typedef struct {
  uint64_t extracted;
  uint64_t failed;
  bool aborted;
} NtuaReport;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Open an archive at `path`. On success writes the handle to `*out`.

 # Safety
 `path` and `out` must be valid pointers; `opts` may be null.
 */
NtuaStatus ntua_open(const char *path, const NtuaOpenOptions *opts, NtuaArchive **out);

/*
 Number of entries in the archive (0 if `ar` is null).

 # Safety
 `ar` must be a handle from `ntua_open` (or null).
 */
uintptr_t ntua_entry_count(const NtuaArchive *ar);

/*
 Fill `*out` with a borrowed view of entry `idx`.

 # Safety
 `ar` must be a valid handle; `out` must be a valid pointer.
 */
NtuaStatus ntua_entry_at(const NtuaArchive *ar, uintptr_t idx, NtuaEntry *out);

/*
 Read entry `idx` into a freshly allocated buffer (`*out_buf`/`*out_len`).
 Free it with `ntua_buffer_free`.

 # Safety
 `ar`, `out_buf`, `out_len` must be valid pointers.
 */
NtuaStatus ntua_read_entry(NtuaArchive *ar, uintptr_t idx, uint8_t **out_buf, uintptr_t *out_len);

/*
 Extract entries to disk. `cb`/`ctx` may be null (no progress).

 # Safety
 `ar` and `opts` must be valid pointers; `out` may be null.
 */
NtuaStatus ntua_extract(NtuaArchive *ar,
                        const NtuaExtractOptions *opts,
                        NtuaProgressFn cb,
                        void *ctx,
                        NtuaReport *out);

/*
 Free an archive handle. No-op on null.

 # Safety
 `ar` must be a handle from `ntua_open` that has not already been freed.
 */
void ntua_free(NtuaArchive *ar);

/*
 Free a buffer returned by `ntua_read_entry`. No-op on null.

 # Safety
 `buf`/`len` must come from one `ntua_read_entry` call, freed at most once.
 */
void ntua_buffer_free(uint8_t *buf, uintptr_t len);

/*
 Localized message for a status code, via `newtua-i18n`. `lang` is a locale
 code (e.g. "en"/"ru") or null for auto. Returns an owned string; free with
 `ntua_string_free`. Dynamic detail (paths, counts) is not included.

 # Safety
 `lang` may be null; if non-null it must be a valid C string.
 */
char *ntua_error_message(NtuaStatus status, const char *lang);

/*
 Free a string returned by `ntua_error_message`. No-op on null.

 # Safety
 `s` must come from `ntua_error_message`, freed at most once.
 */
void ntua_string_free(char *s);

/*
 The crate version (static, NUL-terminated). Do not free.
 */
const char *ntua_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NEWTUA_H */
