#!/usr/bin/env bash
#
# Builds Newtua.xcframework from the published newtua-ffi crate.
#
# The source is fetched from crates.io rather than read out of a neighbouring
# checkout: this package is released on its own, and the artefact it ships must
# correspond to a version anyone can inspect. Pass the crate version as the
# first argument (default: the FFI_VERSION below).
#
# Requires: a Rust toolchain with both Apple targets, and Xcode's xcodebuild.
#
set -euo pipefail

FFI_VERSION="${1:-0.1.0}"

FRAMEWORK_NAME="CNewtua"
FRAMEWORK_VERSION="A"
DEPLOYMENT_TARGET="14.0"
TARGETS=(aarch64-apple-darwin x86_64-apple-darwin)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
XCFRAMEWORK_PATH="$REPO_ROOT/Newtua.xcframework"
INSTALL_NAME="@rpath/$FRAMEWORK_NAME.framework/Versions/$FRAMEWORK_VERSION/$FRAMEWORK_NAME"

BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

echo "==> Fetching newtua-ffi $FFI_VERSION from crates.io"
# crates.io answers 403 to requests without a User-Agent — it is not optional.
curl -sSfL -H "User-Agent: newtua-swift build script (github.com/new-the-unarchiver/newtua-swift)" \
    "https://crates.io/api/v1/crates/newtua-ffi/$FFI_VERSION/download" \
    -o "$BUILD_DIR/crate.tar.gz"
tar xzf "$BUILD_DIR/crate.tar.gz" -C "$BUILD_DIR"
CRATE_DIR="$BUILD_DIR/newtua-ffi-$FFI_VERSION"

# The deployment floor lives with the Apple package, not with the
# cross-platform crate — hence an env var rather than anything in Cargo.toml.
export MACOSX_DEPLOYMENT_TARGET="$DEPLOYMENT_TARGET"

for target in "${TARGETS[@]}"; do
    echo "==> Building $target"
    rustup target add "$target" >/dev/null 2>&1 || true
    (cd "$CRATE_DIR" && cargo build --release --target "$target" --quiet)
done

# Both Apple slices belong to one platform, so an XCFramework wants them merged
# into a single universal binary — not two separate slices, which xcodebuild
# rejects as a duplicate platform.
echo "==> Merging into a universal binary"
FRAMEWORK_DIR="$BUILD_DIR/$FRAMEWORK_NAME.framework"
VERSION_DIR="$FRAMEWORK_DIR/Versions/$FRAMEWORK_VERSION"
mkdir -p "$VERSION_DIR/Headers" "$VERSION_DIR/Modules" "$VERSION_DIR/Resources"

lipo -create \
    "$CRATE_DIR/target/aarch64-apple-darwin/release/libnewtua_ffi.dylib" \
    "$CRATE_DIR/target/x86_64-apple-darwin/release/libnewtua_ffi.dylib" \
    -output "$VERSION_DIR/$FRAMEWORK_NAME"
install_name_tool -id "$INSTALL_NAME" "$VERSION_DIR/$FRAMEWORK_NAME"

# The header is the one generated by the crate's own build script, so it always
# describes exactly the library sitting beside it.
cp "$CRATE_DIR/include/newtua.h" "$VERSION_DIR/Headers/newtua.h"

cat > "$VERSION_DIR/Modules/module.modulemap" <<EOF
framework module $FRAMEWORK_NAME {
    umbrella header "newtua.h"
    export *
    module * { export * }
}
EOF

cat > "$VERSION_DIR/Resources/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>     <string>en</string>
    <key>CFBundleExecutable</key>            <string>$FRAMEWORK_NAME</string>
    <key>CFBundleIdentifier</key>            <string>org.newtua.$FRAMEWORK_NAME</string>
    <key>CFBundleInfoDictionaryVersion</key> <string>6.0</string>
    <key>CFBundleName</key>                  <string>$FRAMEWORK_NAME</string>
    <key>CFBundlePackageType</key>           <string>FMWK</string>
    <key>CFBundleShortVersionString</key>    <string>$FFI_VERSION</string>
    <key>CFBundleVersion</key>               <string>1</string>
    <key>MinimumOSVersion</key>              <string>$DEPLOYMENT_TARGET</string>
</dict>
</plist>
EOF

# Symlink layout that xcodebuild -create-xcframework expects.
(cd "$FRAMEWORK_DIR/Versions" && ln -sfn "$FRAMEWORK_VERSION" Current)
(cd "$FRAMEWORK_DIR" \
    && ln -sfn "Versions/Current/$FRAMEWORK_NAME" "$FRAMEWORK_NAME" \
    && ln -sfn Versions/Current/Headers Headers \
    && ln -sfn Versions/Current/Modules Modules \
    && ln -sfn Versions/Current/Resources Resources)

echo "==> Creating the XCFramework"
rm -rf "$XCFRAMEWORK_PATH"
xcodebuild -create-xcframework -framework "$FRAMEWORK_DIR" -output "$XCFRAMEWORK_PATH" >/dev/null

EMBEDDED_BIN="$XCFRAMEWORK_PATH/macos-arm64_x86_64/$FRAMEWORK_NAME.framework/Versions/$FRAMEWORK_VERSION/$FRAMEWORK_NAME"
if [[ ! -f "$EMBEDDED_BIN" ]]; then
    echo "error: xcodebuild did not produce $EMBEDDED_BIN" >&2
    exit 1
fi

# A wrong install_name only fails at run time, inside a host app — check it here
# where the failure is cheap to read.
ACTUAL=$(otool -D "$EMBEDDED_BIN" | tail -n 1 | tr -d '[:space:]')
if [[ "$ACTUAL" != "$INSTALL_NAME" ]]; then
    echo "error: install_name mismatch" >&2
    echo "  got:      $ACTUAL" >&2
    echo "  expected: $INSTALL_NAME" >&2
    exit 1
fi

echo "==> Packaging"
(cd "$REPO_ROOT" && rm -f Newtua.xcframework.zip \
    && zip -qry Newtua.xcframework.zip Newtua.xcframework)

echo
echo "OK: $XCFRAMEWORK_PATH ($(lipo -archs "$EMBEDDED_BIN"))"
echo "    $REPO_ROOT/Newtua.xcframework.zip"
echo "    checksum: $(cd "$REPO_ROOT" && swift package compute-checksum Newtua.xcframework.zip)"
